### ISSUE TITLE
special character in p300 README

### ISSUE THREAD

**Issue by cll008** [sccn/bids-matlab-tools-example#2]
p300 testcase results in `false` for `isequaln` comparisons because README is different.
Looks like[ the last '10 10' used in README in bids_export_example_p300 ](https://github.com/sccn/bids-matlab-tools-testcase/blob/f85f86b4549ddb9d7b00ac05dd98236f66ae6ffc/p300study/bids_export_example_p300.m#L20)is not exported correctly.
Not sure if we need to update BIDS to accommodate special characters at the end of strings or change the p300 script.

```
tmp1 = rmfield(ALLEEG1(1).BIDS.gInfo, 'README');
tmp2 = rmfield(ALLEEG2(1).BIDS.gInfo, 'README');
isequaln(tmp1,tmp2)  == 1
```

**Comment by arnodelorme** [comment]
Fixed. Tx
